### ISSUE TITLE
[Feat] 좋아요 숫자 조회를 위한 메서드 구현

### ISSUE THREAD

**Issue by wondo8449** [LeeChangHyeong/igeo-mubwotna#33]
**🌟 Issue : Feature**
좋아요 조회와 관련된 기능 구현

**Description**
각 레시피와 댓글의 좋아요 숫자를 조회하기 위한 메서드 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] RecipeLikesRepository에 쿼리메서드 추가
- [ ] CommentLikesRepository에 쿼리메서드 추가
- [ ] LikeService에 좋아요 숫자 조회 메서드 추가
