### ISSUE TITLE
[refactoring] comment 코드 정리

### ISSUE THREAD

**Issue by eunsaemsaem** [LeeChangHyeong/igeo-mubwotna#44]
**🌟 Issue : Feature**
comment와 관련한 코드 리펙토링

**Description**
comment와 관련하여 작성한 코드들을 수정합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] updateComment 시 return 값 수정
- [x] commentResponse의 message 제거
- [x] 예외처리 메서드로 만들기

**Reference(Optional)**
